### ISSUE TITLE
Freenode's #jollafanclub is owned by a placeholder account 

### ISSUE THREAD

**Issue by Mikaela** [sailfishos-community/awesome-sailfishos#14]
*This may not be the best possible place to report this, but I have brought it to attention on the channel itself (without getting any feedback) and I cannot think of any other place where I could ticket this.*

The freenode channel #jollafanclub is owned by freenode-placeholder-account, probably due to the previous founder not logging in enough recently before freenode services database purge that previously happened during easter.

I think someone representing the project should perform group registration with freenode and claim the ownership of the channel back.

* https://freenode.net/news/scheduled-maintenance-services-database-spring-cleaning
* https://freenode.net/groupreg

Currently there are a couple of ops with ChanServ flags `+AORVefiorstv`, me, Cybette and Thaodan. While we can perform day-to-day tasks and some rarer ones, this situation isn't optimal.

**Comment by Thaodan** [comment]
Which tasks are needed for from the channel owner? I'd maybe take them as I'm maintaining the bridge already.

**Comment by Mikaela** [comment]
I think you need to ask `/stats p` or `#freenode` on how to regain the ownership if it's possible as the channel is currently on wrong namespace.

I would also suggest you to register the bot and give it `/msg chanserv flags #jollafanclub botaccount +V` so it will get automatically voiced and possibly higher limits on freenode's antispam measures.

**Comment by Thaodan** [comment]
The channel owner is the successor to the founder in that case? chanserv info is not really clear on that.

**Comment by Mikaela** [comment]
Owner and founder are the same thing in Atheme IRC Services that freenode uses.

**Comment by MichaelTunnell** [comment]
this happened due to the freenode purge earlier in the year. Any account not seen for 90 days earlier in the year was deleted and any channel associated to those users were vacated and taken over by the placeholder account.

**Comment by Thaodan** [comment]
Superseded by #17
