### ISSUE TITLE
Switch away from freenode

### ISSUE THREAD

**Issue by Thaodan** [sailfishos-community/awesome-sailfishos#17]
As the Freenode drama is increasing I think we should move somewhere else .[1]
Now since they switched the IRC server and services package which results in netsplits, the Nickserv db to be reset and all registered channels to be gone. [2]

Currently most projects either move to either OFTC or Libera.chat.
I would suggest to move to OFTC since Jolla will move their channels to OFTC.

---
[1] https://teddit.namazso.eu/r/linux/comments/o0263h/all_freenode_channels_and_users_gone/&theme=auto
[2] https://www.devever.net/~hl/freenode_suicide

**Comment by Thaodan** [comment]
See also:
https://forum.sailfishos.org/t/sailfish-os-irc-channels-moved-to-oftc-net/6980

**Comment by topiasv** [comment]
We can move #jollafanclub to OFTC under a new name, #sfosfanclub that will better match the current name of the community.

**Comment by Thaodan** [comment]
Should the IRC channel not match the telegramchannel name?
#sailfoshos-community sounds fine to me.

**Comment by topiasv** [comment]
didn't want a too long name so I chose #sfosfanclub.

**Comment by Thaodan** [comment]
The other sailfishos channel are named in the long name please name it that 
way too so it is consistent.

**Comment by Mikaela** [comment]
What is the current channel? I am alone on #sfosfanclub at OFTC, not even ChanServ is there.

**Comment by Mikaela** [comment]
Sorry, wrong button.

**Comment by Thaodan** [comment]
> What is the current channel? I am alone on #sfosfanclub at OFTC, not even ChanServ is there.

#sailfishos-fanclub
