### ISSUE TITLE
Add Signal Fan Club

### ISSUE THREAD

**Issue by Logic-gate** [sailfishos-community/awesome-sailfishos#21]
A few users who use Signal have created a Signal Fan Club group.

Group Link: https://signal.group/#CjQKIAq0Wqusuhku1jYnt0hnGrIMmEVEWyzGxpIotkJkbguREhBZ6qdYOtNwLhXJ-KPoPs1D

**Comment by Mikaela** [comment]
I am a bit unsure about this, it would be the first listed Signal group and I wonder if it would need to have warning about Signal sharing phone numbers to others in groups.

Additionally what is the status of native Signal in SailfishOS? Does participation require an Android app or using another OS?

**Comment by Logic-gate** [comment]
Hey Mikaela,

>if it would need to have warning about Signal sharing phone numbers to others in groups.

That is a fair disclaimer to have. Although I have been notified that there is work currently underway to enable usernames instead of numbers. So maybe once that is implemented, the warning can be discarded.

>Additionally what is the status of native Signal in SailfishOS? Does participation require an Android app or using another OS?

It it usable using Whisperfish. WF is under active development and many features are being added and bugs are being squashed with every update. I would refer you to the project page to gauge the the state of Whisperfish here: https://gitlab.com/whisperfish/whisperfish

As far as I can tell, all the basic features to "converse" are functional. Some users might use it as a secondary app; having the Android one being the main. However, it can, and is used by as the main app for some.
